### ISSUE TITLE
TODO: run optimise_predictions.R with new code in main

### ISSUE THREAD

**Issue by andrewbaxter439** [andrewbaxter439/UC-DiD-analysis#7]
Hi @vkhodygo - have updated the code in the `optimise_predictions.R` file to run a full set of optimising predictions. Will be a little longer than trial versions. Could you run then send the `.rds` files from the `output` folder (via email or onedrive)?

Most things fixed and should run smoothly, but let me know if not.

**Comment by vkhodygo** [comment]
Affirmative.

**Comment by vkhodygo** [comment]
OK, the problem with the number of cores persists, I had to hardcode the number.

**Comment by andrewbaxter439** [comment]
Am now able to access workstation 👍
